name: CI Build and Test

on:
  pull_request:
    branches:
      - main  # ou a sua branch principal, por exemplo, 'develop'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executar testes com JaCoCo
        run: mvn clean verify

      # Opcional: Adicionar um passo para publicar o relatório de cobertura
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: target/site/jacoco